config/routes.rb
Rubazzle::Application.routes.draw do
  resources :orders
  get 'specials' => 'orders#special'

  get 'before_after/compare'

  root :to => "home#index"
  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users
end

app/models/order.rb
class Order < ActiveRecord::Base
	belongs_to :user
end

app/models/user.rb
require Rails.root.join('lib', 'devise', 'encryptors', 'md5')

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable 
         #,:encryptable, :encryptor => :md5

  enum role: [:user, :vip, :admin]
  after_initialize :set_default_role, :if => :new_record?

  validates_format_of :rewards_code, :with => /^[a-z0-9]+$/i, :multiline => true, :allow_blank => true

  def set_default_role
    self.role ||= :user
  end

#def password_salt
#end

#def password_salt=(new_salt)
#end

#  def valid_password?(password)
#  	puts "password #{password} encrypted password #{encrypted_password}"
#  	puts Devise::Encryptable::Encryptors::Md5.digest("password", nil, nil, nil)
#  	return false if ! encrypted_password
#  	return false if encrypted_password.blank?
#  	Devise.secure_compare(Devise::Encryptable::Encryptors::Md5.digest(password, nil, nil, nil), self.encrypted_password)
#  end

  protected
	def confirmation_required?
    	false
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  def track_partner
    logger.debug("Request tracked from partner: #{request.env["HTTP_REFERER"]}")
  end

  private

  def user_not_authorized
    flash[:alert] = "Access denied."
    redirect_to (request.referrer || root_path)
  end

end

app/controllers/before_after_controller.rb
class BeforeAfterController < ApplicationController
  def compare
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :track_partner
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET /orders
  # GET /orders.json
  def index
    email = current_user.email

    @orders = Order.joins(:user).where("users.email LIKE '" + email + "'")
    #@qualifying_orders = Order.where("rewards_code = '#{current_user.rewards_code}'")
  end

  def special
    @orders = Order.where("rewards_code = '#{current_user.rewards_code}'")
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)
    @order.user_id = current_user.id
    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(params.permit!)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:product, :quantity, :price, :cc, :cvv, :expiration, :first_name, :last_name)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  before_filter :update_sanitized_params, if: :devise_controller?

  def update_sanitized_params
    devise_parameter_sanitizer.for(:sign_up) {|u| u.permit(:name, :email, :password, :password_confirmation)}
    devise_parameter_sanitizer.for(:account_update) {|u| u.permit(:name, :email, :password, :password_confirmation, :current_password, :rewards_code)}
  	
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  after_action :verify_authorized, except: [:show]

  def index
    @users = User.all
    authorize @users
  end

  def show
    @user = User.find(params[:id])
    unless current_user.admin?
      unless @user == current_user
        redirect_to root_path, :alert => "Access denied."
      end
    end
  end

  def update
    @user = User.find(params[:id])
    authorize @user
    if @user.update_attributes(user_params)
      redirect_to users_path, :notice => "User updated."
    else
      redirect_to users_path, :alert => "Unable to update user."
    end
  end

  def destroy
    user = User.find(params[:id])
    authorize user
    unless user == current_user
      user.destroy
      redirect_to users_path, :notice => "User deleted."
    else
      redirect_to users_path, :notice => "Can't delete yourself."
    end
  end

  private

  def user_params
    params.permit!
    # params.require(:user).permit(:rewards_code)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def display_base_errors resource
    return '' if (resource.errors.empty?) or (resource.errors[:base].empty?)
    messages = resource.errors[:base].map { |msg| content_tag(:p, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-block">
      <button type="button" class="close" data-dismiss="alert">&#215;</button>
      #{messages}
    </div>
    HTML
    html.html_safe
  end

end

app/helpers/before_after_helper.rb
module BeforeAfterHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/before_after/compare.html.erb
  
<div class="container">

<div class="col-xs-12 text-center">
	<h3>Before and After</h3>
</div>
<div class="col-xs-12 text-center">
	<div class="col-xs-5">
		<%= image_tag "old.jpeg" %>
	</div>
	<div class="col-xs-1">
		<h1>|</h1>
	</div>
	<div class="col-xs-5">
		<%= image_tag "new.jpeg" %>
	</div>
</div>
</div>

app/views/home/index.html.erb
<h1>Rubazzle: </h1>  
<div class="container">
<div class="col-xs-12">
	<div class="col-xs-3">
		<%= image_tag "rubies1.png" %>
	</div>
	<div class="col-xs-1">
		<h1>+</h1>
	</div>
	<div class="col-xs-3">
		<%= image_tag "macs1.jpeg" %>
	</div>
	<div class="col-xs-1">
		<h1>=</h1>
	</div>
	<div class="col-xs-3">
		<%= image_tag "rubazzle.jpeg" %>
	</div>

</div>
</div>

app/views/layouts/_footer.html.erb
<div class="col-xs-12 text-center">

    <a href="https://twitter.com/rubazzle" class="twitter-follow-button" data-show-count="false" data-size="large" data-dnt="true">Follow @rubazzle</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>

</div>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Rubazzle', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
        <%= render 'layouts/navigation_links' %>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

<%# Left justified items %>				 
<ul class="nav navbar-nav navbar-left">
	<% if user_signed_in? %>
  	<li class="nav"><%= link_to 'Compare', before_after_compare_path %>
  	</li>
	<li>
		<%= link_to 'Order', new_order_path %>
	</li>

	<% end %>					
</ul>

<ul class="nav navbar-nav navbar-right">
  <% if user_signed_in? %>
    <li><%= link_to 'Edit account', edit_user_registration_path %></li>
    <li><%= link_to 'Logout ('+current_user.name+')', destroy_user_session_path, :method=>'delete' %></li>
  <% else %>
    <li><%= link_to 'Login', new_user_session_path %></li>
    <li><%= link_to 'Sign up', new_user_registration_path %></li>
  <% end %>
  <% if user_signed_in? %>
    <li><%= link_to 'Users', users_path %></li>
  <% end %>

</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Rubazzle" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Rubazzle" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= favicon_link_tag 'favicon.ico' %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
    <footer>
      <%= render 'layouts/footer' %>
    </footer>
  </body>
</html>

app/views/orders/_form.html.erb
<%= simple_form_for(@order) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :product %>
    <%= f.input :quantity %>
    <%= f.input :price %>
    <%= f.input :cc %>
    <%= f.input :cvv %>
    <%= f.input :expiration %>
    <%= f.input :first_name %>
    <%= f.input :last_name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/orders/edit.html.erb
<h1>Editing order</h1>

<%= render 'form' %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<h1>Listing orders</h1>

<table>
  <thead>
    <tr>
      <th>Product</th>
      <th>Quantity</th>
      <th>Price</th>
      <th>First name</th>
      <th>Last name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.product %></td>
        <td><%= order.quantity %></td>
        <td><%= order.price %></td>
        <td><%= order.first_name %></td>
        <td><%= order.last_name %></td>
        <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order', new_order_path %>

app/views/orders/new.html.erb
<h1>New order</h1>

<%= render 'form' %>

<%= link_to 'Back', orders_path %>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Product:</strong>
  <%= @order.product %>
</p>  

<p>
  <strong>Quantity:</strong>
  <%= @order.quantity %>
</p>

<p>
  <strong>Price:</strong>
  <%= @order.price %>
</p>


<p>
  <strong>Expiration:</strong>
  <%= @order.expiration %>
</p>

<p>
  <strong>First name:</strong>
  <%= @order.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @order.last_name %>
</p>

<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>

app/views/orders/special.html.erb
<h1>Listing orders</h1>

<table>
  <thead>
    <tr>
      <th>Product</th>
      <th>Quantity</th>
      <th>Price</th>
      <th>First name</th>
      <th>Last name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.product %></td>
        <td><%= order.quantity %></td>
        <td><%= order.price %></td>
        <td><%= order.first_name %></td>
        <td><%= order.last_name %></td>
        <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order', new_order_path %>

app/views/users/_user.html.erb
<td>
  <%= link_to user.email, user %>
</td>
<td>
  <%= form_for(user) do |f| %>
    <%= f.select(:role, User.roles.keys.map {|role| [role,role]}) %>
    <%= f.submit 'Change Role', :class => 'button-xs' %>
  <% end %>
</td>
<td>
  <%= link_to("Delete user", user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'button-xs') unless user == current_user %>
</td>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h3>Users</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h3>User</h3>
<p>Email: <%= @user.email if @user.email %></p>